# Generated by Django 5.2.4 on 2025-07-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_white', models.CharField(max_length=150)),
                ('player_black', models.CharField(blank=True, max_length=150, null=True)),
                ('board_fen', models.TextField(default='startpos')),
                ('turn', models.CharField(default='white', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('room_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameRematchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100, unique=True)),
                ('player_white', models.CharField(max_length=100)),
                ('player_black', models.CharField(max_length=100)),
                ('white_ready', models.BooleanField(default=False)),
                ('black_ready', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
