# Generated by Django 5.2.4 on 2025-07-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_delete_gamerematchstatus_game_black_rematch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
