# Generated by Django 5.2.4 on 2025-07-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time_per_player',
            field=models.IntegerField(default=5),
        ),
    ]
